### ISSUE TITLE
Auto install crashes on enveomics.R

### ISSUE THREAD

**Issue by lmrodriguezr** [lmrodriguezr/enveomics-gui#32]
Issue migrated from lmrodriguezr/enveomics#19 @cpadilla7:

> Hello,
> 
> Whenever I try to run auto install enveomics.r auto install from the GUI the program stalls then crashes, any suggestions?
> 
> Thanks!

**Comment by lmrodriguezr** [comment]
Hello @cpadilla7,
Which version of R do you have? Please send the output of this command from the terminal: `R --version`.
Have you had any problems auto-installing any other requirements?

**Comment by cpadilla7** [comment]
The output is - 
R --version
R version 3.2.4 (2016-03-10) -- "Very Secure Dishes"

**Comment by cpadilla7** [comment]
Oh, also I haven't tired to auto-install anything else from the GUI

**Comment by lmrodriguezr** [comment]
That's very strange, any R 3.2 should support this package. Please run this in the terminal and let me know what the output is:

```
echo 'install.packages("enveomics.R", repos="http://cran.r-project.org")' | R --vanilla
```

Thanks for your report!

**Comment by cpadilla7** [comment]
Here's the output from that command:
R version 3.2.4 (2016-03-10) -- "Very Secure Dishes"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin13.4.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> install.packages("enveomics.R", repos="http://cran.r-project.org")
> Installing package into ‘/Users/cpadilla/Library/R/3.2/library’
> (as ‘lib’ is unspecified)
> trying URL 'http://cran.r-project.org/bin/macosx/mavericks/contrib/3.2/enveomics.R_1.0.1.tgz'
> 
> # Content type 'application/x-gzip' length 125729 bytes (122 KB)
> 
> downloaded 122 KB

The downloaded binary packages are in
    /var/folders/2h/122wkyls4qv5hfqsbrcj7ldm0000gn/T//RtmpdGJpHK/downloaded_packages

**Comment by cpadilla7** [comment]
I think I figured it out... stupid really, 

I didn't have R in my path, I've only been using the R GUI not the linux command line version... I tried on my work computer where it is set up correctly and it ran like charm...  sorry for the confusion, and thanks so much for your help!
